console.log('Starting')
let url = 'https://gusbus.space/DoodleBot.html'
console.log(JSON.stringify(ring))
// let data = JSON.parse('./ring.json')
console.log(ring.length)
console.log(url+' index:')
currentIdx = ring.map(x => x.url).indexOf(url)
console.log(currentIdx)
console.log('Next url:')
console.log(ring[currentIdx + 1].url)
